### PR TITLE
Tokenizer, clitics- and tokenization-related fixes (replaces #84 & #88)

### LINKED ISSUE #69: create StextualDS.tokenize()
create method tokenize() for STextualDs for a fast access.

### LINKED ISSUE #86: Tokenizer sets Italian (?) clitics to LanguageCode for Spanish
Cf. https://github.com/korpling/salt/blob/3fe7e613a9ff52a00e57b33cef2a17da6a724f95/salt-api/src/main/java/org/corpus_tools/salt/common/tokenizer/Tokenizer.java#L333-L334

I'm not a speaker of Italian, but I do know a little Spanish. I've never seen any of the clitics above in Spanish, but am sure I've seen at least some of them on menus in pizzerias :wink:.

### LINKED ISSUE #87: Proclitics regex for French doesn't work as expected
For tokens like "qu'il", the [regex](https://github.com/korpling/salt/blob/3fe7e613a9ff52a00e57b33cef2a17da6a724f95/salt-api/src/main/java/org/corpus_tools/salt/common/tokenizer/Tokenizer.java#L331) will produce unexpected groups 1 and 2, which will both be "qu'". This breaks the tokenization. I imagine this is because you get the "qu'" expression more than once in the regex, but am not an expert.

### PR DESCRIPTION
**Pull request by sdruskat**
- Fix #69 
- Fix #86 
- Fix #87 
- Add dynamic clitics support, i.e., the ability to set proclitics and enclitics on a specific language (referenced by `LanguageCode`) in `Tokenizer`, similar to how abbreviations work.
- Add tests

### CODE REVIEW

**Comment by sdruskat** [comment]
@thomaskrause: I don't know why it says "wants to merge 70 commits into **korpling:master** from sdruskat:clitics", cos I selected develop as target branch, but I think this can be fixed during the merge process?

**Comment by sdruskat** [comment]
@thomaskrause: Check out https://help.github.com/articles/merging-a-pull-request/, you may want to check this PR out locally and merge into develop...

**Comment by thomaskrause** [comment]
made a new pull request #90 which merges into develop branch

**Comment by thomaskrause** [comment]
@FlorianZipser this was not merged

**Pull request closed without merging**
